### ISSUE TITLE
dependency crypto ^3.0.0

### ISSUE THREAD

**Issue by bananenwilly** [dart-bitcoin/bip39#13]
https://github.com/dart-bitcoin/bip39/blob/78b7deea506711275a165c9eee037ba1f019720b/pubspec.yaml#L13

any harm in bumping this to ^3.0.0 for compatability reasons?

**Comment by bananenwilly** [comment]
https://github.com/dart-bitcoin/bip39/pull/14

one line of code changed.
tests ran fine.

**Comment by cedvdb** [comment]
This would be appreciated

**Comment by longhoangwkm** [comment]
I've published it as https://pub.dev/packages/bip39/versions/1.0.6 version
